Implementing PCEN and providing option to switch
castorini/honk pull request #62
Opened 2019-01-13 17:11 UTC by ljj7975

2019-01-13 18:18 UTC, lintool commented
Do we have evaluation results and comparisons to existing models?

2019-01-13 20:59 UTC, ljj7975 commented
I didn't know there was a ticket for this.
I have compared accuracy but I did not see any difference at least with our current resnets.

I have also tried PCEN provided by librosa but it was actually worse.
We decided to keep MFCCs for now and compare again with convrnn once it is implemented.

2019-01-13 21:12 UTC, ljj7975 commented
One possible reason might be that google data have similar loudness.
in the paper, they augmented their data by scaling the loudness to see the benefit of PCEN.
I will see if that changing loudness pose any accuracy difference when I have time

2019-01-13 22:20 UTC, daemon requested changes
Overall structure looks good. A few minor issues and nitpicks here and there.

2019-01-13 22:20 UTC, daemon commented on utils/manage_audio.py
> +        self.hop_length = sr //1000 * hop_ms
`//` missing space

2019-01-13 22:20 UTC, daemon commented on utils/manage_audio.py
> +    def get_MFCCs(self, data):
I think `compute_mfccs` is a better name.

2019-01-13 22:20 UTC, daemon commented on utils/manage_audio.py
> +    def get_PCEN(self, data):
`compute_pcen`

2019-01-13 22:20 UTC, daemon commented on README.md
> +| `--audio_preprocess_type`   | {MFCCs, PCEN}       | PCEN     | type of audio preprocess to use            |
If the new default is PCEN, then we'll need to update the existing instructions to use MFCCs.

2019-01-13 22:22 UTC, ljj7975 commented on README.md
> +| `--audio_preprocess_type`   | {MFCCs, PCEN}       | PCEN     | type of audio preprocess to use            |
oh ya I updated the code but forgot to update readme

2019-01-14 21:07 UTC, daemon approved these changes

2019-01-14 21:46 UTC, merged

2019-01-23 10:00 UTC, lydiaji commented
> One possible reason might be that google data have similar loudness.
> in the paper, they augmented their data by scaling the loudness to see the benefit of PCEN.
> I will see if changing loudness pose any accuracy difference when I have time

I've also used PCEN, but the result is not as good as I simply use MFCC as features. In the paper, the results with or without multi loudness training makes no much difference. So I wonder why using PCEN does not improve my result? Would you please give me some suggestion? Thanks!

2019-01-23 13:08 UTC, daemon commented
My guess is that you'd have to see more loudness variability in your audio data for PCEN to be useful, as is the case for more extreme near- and far-field settings, e.g., person talking 1cm away from mic vs. 5ft. Also, in the original paper they compare only to log-Mels, not MFCCs -- whether this makes a difference for deep neural nets is unclear, since MFCCs are just a linear map over log-Mels.

2019-01-25 05:07 UTC, lydiaji commented
> My guess is that you'd have to see more loudness variability in your audio data for PCEN to be useful, as is the case for more extreme near- and far-field settings, e.g., person talking 1cm away from mic vs. 5ft. Also, in the original paper they compare only to log-Mels, not MFCCs -- whether this makes a difference for deep neural nets is unclear, since MFCCs are just a linear map over log-Mels.

Thanks for your reply. I have just noticed that I didn't use multi-loudness training. In the paper, for fixed PCEN, its accuracy with or without multi-loudness training performs similar. While for trainable PCEN, it needs multi-loudness training. So would it be a reason that the result is not so good?

2019-01-25 08:23 UTC, lydiaji commented
In addition, I didn't use streaming data. Would it be a problem for computing iir filter? In the paper, it showed that 23 left context frames and 9 right context frames as input to the net. I'm not clear about how to implement that? Would you please give me some guide? Thanks!!!