script for generating youtube crawler evaluation data
castorini/honk pull request #64
Opened 2019-01-18 01:14 UTC by ljj7975

The first milestone is generate a evaluation framework and dataset which we can measure our improvements.

the dataset need to be labelled, i.e. for given audio block. we have to check if the audio actually contains keyword.
`evaluation_data_generator.py` is the script which plays section of audio and ask how many times the keyword was spoken.
It will generate csv, where each column represent `url, start_ms, end_ms, cc_count, audio_count` where cc_count is how many it appeared in subtitle and audio_count is the user's response
This csv file will be what we will use for running evaluation

We may need to work on the same set of videos but putting video dataset on github is nonsense. 
`url_file_generator.py` generates .txt file containing valid urls.
Note that this script will be run once and .txt file generated will be used for `evaluation_data_generator.py`

2019-01-18 02:08 UTC, lemoz commented
Amazing! Was going to create this but did not think to look at the captions to reduce the search space!

2019-01-20 21:59 UTC, daemon requested changes
Just minor issues.

2019-01-20 21:59 UTC, daemon commented on keyword_spotting_data_generator/evaluation/evaluation_data_generator.py
> +from pytube import YouTube as PyTube
Import blocks need one line between them, e.g.,
```
import argparse
import time

import requests
import six

from . import Foobar
```

2019-01-20 21:59 UTC, daemon commented on keyword_spotting_data_generator/evaluation/evaluation_data_generator.py
> +API_KEY = "< API_KEY >"
Maybe allow API key to be set using the commandline argument `--api_key`?

2019-01-20 21:59 UTC, daemon commented on keyword_spotting_data_generator/evaluation/url_file_generator.py
> +API_KEY = "< API_KEY >"
Here as well.

2019-01-20 22:42 UTC, merged