Calculate Edit Distance
castorini/honk pull request #77
Opened 2019-03-12 22:39 UTC by DavidHLi

This implementation has O(mn) time complexity and O(n) space complexity.
It's possible to explore more efficient algorithms such as Ukkonen's algorithm for O(m + d^2) run time, where d = edit distance, but since the two windows calculated by MFCC have length 101, so the difference would be minimal.
One thing I'm uncertain about is whether we should use strict equality to compare floats. For example, should 0.0035 == 0.0036 yields false for our purpose?

2019-03-12 23:18 UTC, ljj7975 requested changes
Nice! Good job!
just a minor variable name change.

You are right. we can't use use strict equality directly.
That is the main reason why we are using VQ before we compute edit_distance.
Throughout VQ we are clustering a range of values and for each input, we emit center of the cluster it belongs to.
so that we can use strict equality for edit distance :)

2019-03-12 23:18 UTC, ljj7975 commented on keyword_spotting_data_generator/evaluation/extractor/edit_distance_extractor.py
> +        M = [[i for i in range(len(self.processed_target) + 1)],
Can you rename this variable? something like `distances` might be a good name

2019-03-12 23:53 UTC, DavidHLi commented
Ahhh finally understood vector quantization, thanks

2019-03-13 00:07 UTC, ljj7975 approved these changes

2019-03-13 00:07 UTC, merged